### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by animegasan** [akosiramnad/OpenWrt-PPPoE-Server-Account-Manager#1]
Hi, I am very interested in your IPK. Is there any source code for me to rebuild on arm architecture?

**Comment by akosiramnad** [comment]
ok sir, I will build IPK for arm architecture, just wait until i finished the update for the version 23 firmware.

**Comment by animegasan** [comment]
What if I help?
I will build for several architectures

**Comment by akosiramnad** [comment]
> What if I help? I will build for several architectures

I'm glad that you want to help sir,
but I already finished building for my next release and it can be install to all architecture

**Comment by animegasan** [comment]
> > What if I help? I will build for several architectures
> 
> I'm glad that you want to help sir, but I already finished building for my next release and it can be install to all architecture

OK, I'll wait for the good news.

I will temporarily close this issue, thank you
