### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by animegasan** [akosiramnad/OpenWrt-PPPoE-Server-Account-Manager#2]
![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/83dfa46f-f27a-42b2-8036-20382e97e5ef)

eval
```js
'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
```

poll_status
```js
	poll_status: function (nodes, data) {
		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
		rules.sort(function (a, b) {
			return a.id - b.id;
		});
		var n = 0;
		var rows = rules.map(function (rule) {
			n = n + 1;
			var newDate = new Date(parseInt(rule.expiry*1000));
			var today = new Date();
			var ts = today.getTime();
			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
				E('button', {
					'class': 'btn cbi-button-edit',
					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
				}, _('Edit')), ' ',
				E('button', {
					'class': 'btn cbi-button cbi-button-remove important',
					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
				}, _('Remove'))
			])];
		});

		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));

		return;
```

**Comment by animegasan** [comment]
![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/fdf426c3-ca13-4f9a-953a-385208ed4259)

**Comment by akosiramnad** [comment]
> ![image](https://private-user-images.githubusercontent.com/14136053/303852803-83dfa46f-f27a-42b2-8036-20382e97e5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODY3NDYsIm5iZiI6MTcwNzU4NjQ0NiwicGF0aCI6Ii8xNDEzNjA1My8zMDM4NTI4MDMtODNkZmE0NmYtZjI3YS00MmIyLTgwMzYtMjAzODJlOTdlNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE3MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjAxZTM0M2M4YzEzMjE2ZWM0Zjk3OTdiMGFiYTVjNmM5YzhhODI2ZGQwMjViOTliNjJlYTliZGQ0MDAxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQdb38D7tGXv_Jb78xYTqqKNUV3OnDLtbKPCC6YCDkk)
> 
> eval
> 
> ```js
> 'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> ```
> 
> poll_status
> 
> ```js
> 	poll_status: function (nodes, data) {
> 		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
> 		rules.sort(function (a, b) {
> 			return a.id - b.id;
> 		});
> 		var n = 0;
> 		var rows = rules.map(function (rule) {
> 			n = n + 1;
> 			var newDate = new Date(parseInt(rule.expiry*1000));
> 			var today = new Date();
> 			var ts = today.getTime();
> 			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
> 			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
> 				E('button', {
> 					'class': 'btn cbi-button-edit',
> 					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> 				}, _('Edit')), ' ',
> 				E('button', {
> 					'class': 'btn cbi-button cbi-button-remove important',
> 					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
> 				}, _('Remove'))
> 			])];
> 		});
> 
> 		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));
> 
> 		return;
> ```

what firmware version you are using sir

**Comment by animegasan** [comment]
Typo in No table

From this
```js
E('th', { 'class': 'th' }, _('No.')),
```
To this
```js
E('th', { 'class': 'th' }, _('No')),
```

**Comment by animegasan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/14136053/303852803-83dfa46f-f27a-42b2-8036-20382e97e5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODY3NDYsIm5iZiI6MTcwNzU4NjQ0NiwicGF0aCI6Ii8xNDEzNjA1My8zMDM4NTI4MDMtODNkZmE0NmYtZjI3YS00MmIyLTgwMzYtMjAzODJlOTdlNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE3MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjAxZTM0M2M4YzEzMjE2ZWM0Zjk3OTdiMGFiYTVjNmM5YzhhODI2ZGQwMjViOTliNjJlYTliZGQ0MDAxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQdb38D7tGXv_Jb78xYTqqKNUV3OnDLtbKPCC6YCDkk)
> > eval
> > ```js
> > 'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > poll_status
> > ```js
> > 	poll_status: function (nodes, data) {
> > 		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
> > 		rules.sort(function (a, b) {
> > 			return a.id - b.id;
> > 		});
> > 		var n = 0;
> > 		var rows = rules.map(function (rule) {
> > 			n = n + 1;
> > 			var newDate = new Date(parseInt(rule.expiry*1000));
> > 			var today = new Date();
> > 			var ts = today.getTime();
> > 			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
> > 			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
> > 				E('button', {
> > 					'class': 'btn cbi-button-edit',
> > 					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > 				}, _('Edit')), ' ',
> > 				E('button', {
> > 					'class': 'btn cbi-button cbi-button-remove important',
> > 					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
> > 				}, _('Remove'))
> > 			])];
> > 		});
> > 
> > 		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));
> > 
> > 		return;
> > ```
> 
> what firmware version you are using sir

I am using ImmortalWrt version 23.05.1

**Comment by animegasan** [comment]
Would it be possible if the Expiration Date was made optional instead of having to always set it every time the account expires?

And we add a table for the account device status whether it is connected or not to our network.

**Comment by animegasan** [comment]
Maybe this will be your inspiration

```js
			return E('div', {
				'class': 'cbi-section cbi-tblsection'
			}, [E('h3', _('PPPoE Accounts')), table, E('div', { 'class': 'cbi-page-actions' }, [ E('button', {
				'class': 'cbi-button cbi-button-save',
				'click': ui.createHandlerFn(view, 'showAddUser')
			}, _('Add User'))])]);
		}, o, this);
```

Before
![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/e72d0523-c60a-4984-b3f5-aff8ea843114)

After
![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/27d9beca-e212-40f2-ad40-5a98409e435a)

**Comment by animegasan** [comment]
![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/9488e893-9003-42b0-83e1-49b3d0e86fe2)

```js
				return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
					E('button', {
						'class': 'cbi-button cbi-button-edit',
						'click': ui.createHandlerFn(view, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
					}, _('Edit')), ' ',
					E('button', {
						'class': 'cbi-button cbi-button-remove',
						'style': 'margin-left:1em',
						'click': ui.createHandlerFn(view, 'delModal', rule.ipaddr)
					}, _('Remove'))
				])];
			});
```

**Comment by akosiramnad** [comment]
Ok sir, will do your suggestion on the next update

**Comment by animegasan** [comment]
> Ok sir, will do your suggestion on the next update

Maybe later I will add more additional update requests. So I will not close this issue. Thanks

**Comment by akosiramnad** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/14136053/303852803-83dfa46f-f27a-42b2-8036-20382e97e5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODY3NDYsIm5iZiI6MTcwNzU4NjQ0NiwicGF0aCI6Ii8xNDEzNjA1My8zMDM4NTI4MDMtODNkZmE0NmYtZjI3YS00MmIyLTgwMzYtMjAzODJlOTdlNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE3MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjAxZTM0M2M4YzEzMjE2ZWM0Zjk3OTdiMGFiYTVjNmM5YzhhODI2ZGQwMjViOTliNjJlYTliZGQ0MDAxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQdb38D7tGXv_Jb78xYTqqKNUV3OnDLtbKPCC6YCDkk)
> > > eval
> > > ```js
> > > 'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > poll_status
> > > ```js
> > > 	poll_status: function (nodes, data) {
> > > 		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
> > > 		rules.sort(function (a, b) {
> > > 			return a.id - b.id;
> > > 		});
> > > 		var n = 0;
> > > 		var rows = rules.map(function (rule) {
> > > 			n = n + 1;
> > > 			var newDate = new Date(parseInt(rule.expiry*1000));
> > > 			var today = new Date();
> > > 			var ts = today.getTime();
> > > 			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
> > > 			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
> > > 				E('button', {
> > > 					'class': 'btn cbi-button-edit',
> > > 					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > 				}, _('Edit')), ' ',
> > > 				E('button', {
> > > 					'class': 'btn cbi-button cbi-button-remove important',
> > > 					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
> > > 				}, _('Remove'))
> > > 			])];
> > > 		});
> > > 
> > > 		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));
> > > 
> > > 		return;
> > > ```
> > 
> > 
> > what firmware version you are using sir
> 
> I am using ImmortalWrt version 23.05.1

I din't get any error like this while installing the package in my newifi d2 using immortalWrt version 23.05.1.

![Screenshot 2024-02-11 200334](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/67589626/5d69f5d8-095b-41e0-844e-d281378e4355)
![Screenshot 2024-02-11 200351](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/67589626/5aa4b795-bbba-41d6-860f-1a16e36bf1ce)

**Comment by animegasan** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/14136053/303852803-83dfa46f-f27a-42b2-8036-20382e97e5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODY3NDYsIm5iZiI6MTcwNzU4NjQ0NiwicGF0aCI6Ii8xNDEzNjA1My8zMDM4NTI4MDMtODNkZmE0NmYtZjI3YS00MmIyLTgwMzYtMjAzODJlOTdlNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE3MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjAxZTM0M2M4YzEzMjE2ZWM0Zjk3OTdiMGFiYTVjNmM5YzhhODI2ZGQwMjViOTliNjJlYTliZGQ0MDAxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQdb38D7tGXv_Jb78xYTqqKNUV3OnDLtbKPCC6YCDkk)
> > > > eval
> > > > ```js
> > > > 'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > poll_status
> > > > ```js
> > > > 	poll_status: function (nodes, data) {
> > > > 		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
> > > > 		rules.sort(function (a, b) {
> > > > 			return a.id - b.id;
> > > > 		});
> > > > 		var n = 0;
> > > > 		var rows = rules.map(function (rule) {
> > > > 			n = n + 1;
> > > > 			var newDate = new Date(parseInt(rule.expiry*1000));
> > > > 			var today = new Date();
> > > > 			var ts = today.getTime();
> > > > 			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
> > > > 			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
> > > > 				E('button', {
> > > > 					'class': 'btn cbi-button-edit',
> > > > 					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > > 				}, _('Edit')), ' ',
> > > > 				E('button', {
> > > > 					'class': 'btn cbi-button cbi-button-remove important',
> > > > 					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
> > > > 				}, _('Remove'))
> > > > 			])];
> > > > 		});
> > > > 
> > > > 		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));
> > > > 
> > > > 		return;
> > > > ```
> > > 
> > > 
> > > what firmware version you are using sir
> > 
> > 
> > I am using ImmortalWrt version 23.05.1
> 
> I din't get any error like this while installing the package in my newifi d2 using immortalWrt version 23.05.1.
> 
> ![Screenshot 2024-02-11 200334](https://private-user-images.githubusercontent.com/67589626/303917104-5d69f5d8-095b-41e0-844e-d281378e4355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTM2MjYsIm5iZiI6MTcwNzY1MzMyNiwicGF0aCI6Ii82NzU4OTYyNi8zMDM5MTcxMDQtNWQ2OWY1ZDgtMDk1Yi00MWUwLTg0NGUtZDI4MTM3OGU0MzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMzZmNWRhMWUzZGM3MzRkODZiYmVhZTQ2NmEyMGIxYWZmZTQ5MjRhZGFjZmU0NTI2M2I2NmNjNWFlYWY3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNJ7f_Jf_l9xHL2tjD7gErETRq4W8-QO3UPGSQ05gwU) ![Screenshot 2024-02-11 200351](https://private-user-images.githubusercontent.com/67589626/303917108-5aa4b795-bbba-41d6-860f-1a16e36bf1ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTM2MjYsIm5iZiI6MTcwNzY1MzMyNiwicGF0aCI6Ii82NzU4OTYyNi8zMDM5MTcxMDgtNWFhNGI3OTUtYmJiYS00MWQ2LTg2MGYtMWExNmUzNmJmMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWU0NTEwZmE1NmYzYzBiMDhkN2I1ZjFjNzZkMTUyYTJmNDM4NGRlYTJmNDE2MDgwY2YwYjA3NTk5NTJkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8IAgucj-L-FKfcM61BWjUhX2mg6ltJJIIFRj5ydYKo)

Use Inspect to see the error, and try adding the user.

**Comment by akosiramnad** [comment]
> > Ok sir, will do your suggestion on the next update
> 
> Maybe later I will add more additional update requests. So I will not close this issue. Thanks

Ok, but can you post in the pull request instead of posting here? ✌️

**Comment by akosiramnad** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/14136053/303852803-83dfa46f-f27a-42b2-8036-20382e97e5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODY3NDYsIm5iZiI6MTcwNzU4NjQ0NiwicGF0aCI6Ii8xNDEzNjA1My8zMDM4NTI4MDMtODNkZmE0NmYtZjI3YS00MmIyLTgwMzYtMjAzODJlOTdlNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE3MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjAxZTM0M2M4YzEzMjE2ZWM0Zjk3OTdiMGFiYTVjNmM5YzhhODI2ZGQwMjViOTliNjJlYTliZGQ0MDAxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQdb38D7tGXv_Jb78xYTqqKNUV3OnDLtbKPCC6YCDkk)
> > > > > eval
> > > > > ```js
> > > > > 'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > poll_status
> > > > > ```js
> > > > > 	poll_status: function (nodes, data) {
> > > > > 		var rules = Array.isArray(data[0].accounts) ? data[0].accounts : [];
> > > > > 		rules.sort(function (a, b) {
> > > > > 			return a.id - b.id;
> > > > > 		});
> > > > > 		var n = 0;
> > > > > 		var rows = rules.map(function (rule) {
> > > > > 			n = n + 1;
> > > > > 			var newDate = new Date(parseInt(rule.expiry*1000));
> > > > > 			var today = new Date();
> > > > > 			var ts = today.getTime();
> > > > > 			var stats = ts >= parseInt(rule.expiry*1000) ? "Expired" : "Active";
> > > > > 			return [n, newDate.toDateString(), rule.user, rule.password, rule.ipaddr, stats, E('div', { 'class': 'center' }, [
> > > > > 				E('button', {
> > > > > 					'class': 'btn cbi-button-edit',
> > > > > 					'click': ui.createHandlerFn(this, 'showEditUser', rule.ipaddr, rule.user, rule.password, rule.ipaddr, rule.expiry*1000)
> > > > > 				}, _('Edit')), ' ',
> > > > > 				E('button', {
> > > > > 					'class': 'btn cbi-button cbi-button-remove important',
> > > > > 					'click': ui.createHandlerFn(this, 'delModal', rule.ipaddr)
> > > > > 				}, _('Remove'))
> > > > > 			])];
> > > > > 		});
> > > > > 
> > > > > 		cbi_update_table(nodes.querySelector('#users_table'), rows, E('em', _('There are no account to display.')));
> > > > > 
> > > > > 		return;
> > > > > ```
> > > > 
> > > > 
> > > > what firmware version you are using sir
> > > 
> > > 
> > > I am using ImmortalWrt version 23.05.1
> > 
> > 
> > I din't get any error like this while installing the package in my newifi d2 using immortalWrt version 23.05.1.
> > ![Screenshot 2024-02-11 200334](https://private-user-images.githubusercontent.com/67589626/303917104-5d69f5d8-095b-41e0-844e-d281378e4355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTM2MjYsIm5iZiI6MTcwNzY1MzMyNiwicGF0aCI6Ii82NzU4OTYyNi8zMDM5MTcxMDQtNWQ2OWY1ZDgtMDk1Yi00MWUwLTg0NGUtZDI4MTM3OGU0MzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMzZmNWRhMWUzZGM3MzRkODZiYmVhZTQ2NmEyMGIxYWZmZTQ5MjRhZGFjZmU0NTI2M2I2NmNjNWFlYWY3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNJ7f_Jf_l9xHL2tjD7gErETRq4W8-QO3UPGSQ05gwU) ![Screenshot 2024-02-11 200351](https://private-user-images.githubusercontent.com/67589626/303917108-5aa4b795-bbba-41d6-860f-1a16e36bf1ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTM2MjYsIm5iZiI6MTcwNzY1MzMyNiwicGF0aCI6Ii82NzU4OTYyNi8zMDM5MTcxMDgtNWFhNGI3OTUtYmJiYS00MWQ2LTg2MGYtMWExNmUzNmJmMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWU0NTEwZmE1NmYzYzBiMDhkN2I1ZjFjNzZkMTUyYTJmNDM4NGRlYTJmNDE2MDgwY2YwYjA3NTk5NTJkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8IAgucj-L-FKfcM61BWjUhX2mg6ltJJIIFRj5ydYKo)
> 
> Use Inspect to see the error, and try adding the user.
Tried adding user and no error shown even in the inspect element.
Maybe you should try to clear you browser cache and try again if there is any error show.
![Screenshot_2024-02-11-21-05-57-920_com android chrome](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/67589626/74e655bf-af9f-46b5-a764-8bc33f42e7dc)
![Screenshot_2024-02-11-21-03-06-404_com android chrome](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/67589626/764779b0-b27b-44d4-a1ab-c577949ea06e)

**Comment by animegasan** [comment]
> > > Ok sir, will do your suggestion on the next update
> > 
> > 
> > Maybe later I will add more additional update requests. So I will not close this issue. Thanks
> 
> Ok, but can you post in the pull request instead of posting here? ✌️

Yes, I want to do it. But isn't there a file in this repository that I can pull request?

**Comment by animegasan** [comment]
> Tried adding user and no error shown even in the inspect element.
> Maybe you should try to clear you browser cache and try again if there is any error show.

![image](https://github.com/akosiramnad/OpenWrt-PPPoE-Server-Account-Manager/assets/14136053/087391fc-eff5-499d-a77b-bddc56d7d7e0)

Maybe this can help, and I have cleared the cache
